/// Flutter icons YoshopIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  YoshopIcons
///      fonts:
///       - asset: fonts/YoshopIcons_200722.ttf
///
/// fontFile version 2020.07.22
///
import 'package:flutter/widgets.dart';

class YoshopIcons {
  YoshopIcons._();

  static const _kFontFam = 'YoshopIcons';
  static const dynamic _kFontPkg = null;

  static const IconData y0101_menu =
      IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y0102_store =
      IconData(0xe901, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y0103_cloud =
      IconData(0xe902, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y0104_password =
      IconData(0xe903, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y0105_domain =
      IconData(0xe904, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y0106_device =
      IconData(0xe905, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y0107_document =
      IconData(0xe906, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y0108_group =
      IconData(0xe907, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y0109_schedule =
      IconData(0xe908, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y0201_circledown =
      IconData(0xe909, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y0202_timer =
      IconData(0xe90A, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y0203_calculator =
      IconData(0xe90B, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y0204_numpad =
      IconData(0xe90C, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y0205_list =
      IconData(0xe90D, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y0206_fork =
      IconData(0xe90E, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y0207_booking =
      IconData(0xe90F, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y0208_tag =
      IconData(0xe910, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y0209_link =
      IconData(0xe911, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y0301_2column =
      IconData(0xe912, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y0302_3column =
      IconData(0xe913, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y0303_money =
      IconData(0xe914, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y0304_creditcard =
      IconData(0xe915, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y0305_minus =
      IconData(0xe916, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y0306_plus =
      IconData(0xe917, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y0307_uncheck =
      IconData(0xe918, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y0308_check =
      IconData(0xe919, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y0309_under =
      IconData(0xe91A, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y0401_up =
      IconData(0xe91B, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y0402_trash =
      IconData(0xe91C, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y0403_spread_all =
      IconData(0xe91D, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y0404_trash_all =
      IconData(0xe91E, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y0405_discount =
      IconData(0xe91F, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y0406_calendar =
      IconData(0xe920, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y0407_close =
      IconData(0xe921, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y0408_enter =
      IconData(0xe922, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y0409_back =
      IconData(0xe923, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y0501_filter =
      IconData(0xe924, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y0502_notice =
      IconData(0xe925, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y0503_print =
      IconData(0xe92D, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y0504_devicebarcode =
      IconData(0xe92F, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y0601_addcart =
      IconData(0xe926, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y0602_checklist =
      IconData(0xe927, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y0603_receipt =
      IconData(0xe928, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y0604_border =
      IconData(0xe929, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y0605_config =
      IconData(0xe92A, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y0606_drawer =
      IconData(0xe92B, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y0607_eachitem =
      IconData(0xe92C, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y0703_mark =
      IconData(0xe930, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y0703_bell =
      IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
