import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:flutter/foundation.dart' show SynchronousFuture;
import 'package:flutter/material.dart';

class AppLocalizations {
  static bool showCode = false;
  static bool showUserInputCode = false;
  static String? languageCode;

  AppLocalizations(this.locale);

  final Locale locale;

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static Map<String, Map<String, String>> get langCode => _localizedValues;
  static set langCode(Map<String, Map<String, String>> data) {
    _localizedValues = data;
  }

  static Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'big_pay': "Big Pay",
      'ok': 'Ok',
      'cancel': 'Cancel',
      'yes': 'Yes',
      'no': 'No',
      'add_payment_method': 'Add payment method',
      'share_my_address': 'Share my Address',
      'sent': 'Sent',
      'received': 'Received',
      'transfer_success': 'Transfer success',
      'time': 'Transfer time',
      'from': 'From',
      'to': 'To',
      'tx_id': 'Tx ID',
      'note': 'Note',
      'readset': 'ReadSet',
      'writeset': 'WriteSet',
      'confirm_transfer_information': 'Confirm transfer information',
      'txmessage': 'TxMessage',
      'add': 'Add',
      'balance': 'Balance',
      'contacts': 'Contacts',
      'address': 'Address',
      'enter_phone_number_or_email_address':
          'Enter phone number or Email address',
      'recent': 'Recent',
      'transfer_to': 'Transfer to',
      'enter_address': 'Enter address',
      'my_accounts': 'My addresss',
      'please_select_account_to_use_for_payment':
          'Please select an address to use for payment',
      'enter_your_passcode': 'Enter your passcode',
      'reset_passcode': 'Reset passcode',
      'create_account': 'Create address',
      'create_account_success': 'Create address success',
      'info': 'Information',
      'information': 'Information',
      'fail': 'Fail',
      'success': 'Success',
      'error': 'Error',
      'warning': 'Warning',
      'enter_account_name': 'Enter address name',
      'select_a_coin': 'Select a coin',
      'search_coin': 'Search coin',
      'suggested': 'Suggested',
      'all_coins': 'All coins',
      'sign_up': 'Sign Up',
      'create_your_passcode': 'Create your passcode',
      'add_payment_address': 'Add payment address',
      'payment_address': 'Payment Address',
      'add_payment_method_success': 'Add payment method success',
      'enter_wallet_name': 'Enter wallet name',
      'ex_my_wallet': '(ex: My wallet)',
      'ex_account_name': '(ex: My address)',
      'select_wallet_color': 'Select wallet color',
      'qr_code': 'QR Code',
      'reenter_your_passcode': 'Re-enter your passcode',
      'i_already_have_a_wallet': 'I already have a wallet',
      'already_have_user_account': 'I already have a user account',
      'most_secure_platform_that_makes_it_easy_to_buy_sell_and_store_crypto':
          'Most secure platform that makes it easy to buy, sell, and store crypto',
      'do_not_have_an_account_q': 'Don’t have an account?',
      'login_to_your_account': 'Login to your Account',
      'email_id': 'Email Id',
      'password': 'Password',
      'confirm_password': 'Confirm password',
      'keep_me_logged_in': 'Keep me logged in',
      'login': 'Log In',
      'forgot_your_password_q': 'Forgot your password?',
      'find_password': 'Find Password',
      'my_wallet': 'My Wallet',
      'confirm': 'Confirm',
      'pay': 'Pay',
      'reward': 'Reward',
      'your_accounts_are_no_available': 'Your address are not available',
      'change_password': 'Change password',
      'phone_number': 'Phone number',
      'logout': 'Logout',
      'enter_your_current_password': 'Enter your current password',
      'enter_your_new_password': 'Enter your new password',
      'notification': 'Notification',
      'service_notification': 'Service notification',
      'receive_service_related_notification':
          'Receive service related notification',
      'marketing_notification': 'Marketing notification',
      'receive_marketing_related_notification':
          'Receive marketing related notification',
      'setting': 'Setting',
      'passcode': 'Passcode',
      'payment_method': 'Payment method',
      'add_delete_payment_method': 'Add / delete payment method',
      'others': 'Others',
      'terms_of_service': 'Terms of Service',
      'terms_of_service_view': 'View the Terms of Service',
      'version': 'Version',
      'edit_wallet_name': 'Edit wallet name',
      'welcome_abroad': 'Welcome abroad!',
      'account_has_been_created': 'account has been created',
      'transfer': 'Transfer',
      'reset': 'Reset',
      'max': 'Max',
      'create_new_wallet': 'Create new wallet',
      'create_new_user_account': 'Create new user account',
      'login_fail_please_check_input_field':
          'Login Fail \nPlease check input field',
      'add_account': 'Add Address',
      'delete_account': 'Delete account',
      'delete_account_q': 'Delete account?',
      'profile': 'Profile',
      'app': 'App',
      'continue': 'Continue',
      'please_enter_mobile_number': 'Please enter mobile number',
      'please_enter_valid_mobile_number': 'Please enter valid mobile number',
      'enter_valid_email': 'Enter Valid Email',
      'please_input_text': 'Please input text',
      'name_must_be_more_than_4_charater': 'Name must be more than 4 charater',
      'password_must_be_more_than_6_charater':
          'Password must be more than 6 charater',
      'password_and_confirmation_password_are_different':
          'Password and confirmation password are different',
      'telephone_number_must_be_of_9_12_digit':
          'Telephone Number must be of 9~12 digit',
      'en': 'English',
      'ko': '한국어',
      'kk': 'қазақ',
      'ru': 'ру́сский язы́к',
      'code': 'Code',
      'language_setting': 'Language Setting',
      'language': 'Language',
      'default_language': 'Default Language',
      'add_txmessage': 'Add TxMessage',
      'edit_txmessage': 'Edit TxMessage',
      'enter_message': 'Enter messages...',
      'edit': 'Edit',
      'payment': 'Payment',
      'payment_success': 'Payment success',
      'invalid_passcode': 'Invalid Passcode',
      'invalid_password': 'Invalid Password',
      'qr_scan': 'QR Scan',
      'fail_to_fetch_posts': 'Fail to fetch posts',
      'debug_only': 'Debug Only',
      'scan_qr_code': 'Scan QR code',
      'flash_on': 'Flash On',
      'flash_off': 'Flash Off',
      'front_camera': 'Use front camera',
      'back_camera': 'Use back camera',
      'pause': 'Pause',
      'resume': 'Resume',
      'loading': 'Loading...',
      'mandatory': 'Mandatory',
      'option': 'Option',
      'user_name': 'User Name',
      'i_agree_terms': 'I agree to the terms and conditions.',
      'account_list_is_empty_create_an_account':
          'The address list is empty.\nCreate an address.',
      'enter_mobile_number_for_verification':
          'Please enter your mobile number for verification',
      'send_verification_code': 'Send verification code',
      'verification_number': 'Verification Number',
      'invalid_verification_number':
          'You entered an incorrect verification code.',
      'valid_time_is_expired':
          'The valid time of the verification number is expired.',
      'remaining_time': 'Remaining time',
      're-send': 'Resend',
      'invalid_phonenumber': 'Invalid PhoneNumber',
      'no_registered_tokens': 'There are no registered tokens.',
      'waiting_for_approval': 'Waiting for license approval.',
      'license_pause': 'License has been suspended.',
      'license_disposal': 'License has been disposed.',
      'license_expired': 'License has been expired.',
      'license_invalid': 'License has been invalid.',
      'license_invalid_store':
          'It is not a license for the store you are logged in to. Do you want to reset?',
      'app_update_title': 'App Update',
      'app_update_context': 'App has been updated',
      'update': 'Update',
      'dismiss': 'Dismiss',
      'exit': 'Exit',
      'restart': 'restart',
      'restart_app': 'You must restart the app.',
      'assign_token': 'Assign Token',
      'select_assign_token': 'Select assign token',
      'assigned_token_list': 'Assigned Token List',
      'addable_token_list': 'Addable Token List',
      'krw': 'KRW',
      'no_data_available_now': 'No data available now!',
      'exchange_rate': 'Exchange Rate',
      'assign_token_success': 'Assign Token Success',
      'cancel_assign': 'Cancel Token Assign',
      'remove_account': 'Are you sure you want to delete this address?',
      'transfer_date': 'Date',
      'assign_token_fail': 'Token connection failed. Please try again later',
      'empty_token': 'Empty Token',
      'staking_info': 'Staking',
      'staking_address': 'Staking Address',
      'management': 'Manager',
      'copied': 'Copied',
      'link_has_been_copied_to_clipboard': 'Link has been copied to clipboard.',
      'delete_complete': 'Delete completed',
      'bank_account_delete': 'Bank account deleted successfully.',
      'ethereum': 'Ethereum',
      'vixco': 'VIXCO',
      'delete_wallet': 'Are you sure you want to delete your wallet?',
      'maximum_address': 'You cannot create more than 20 addresses.',
      'mnemonic': 'Mnemonic',
      'invalid_qr_code': 'Invalid QR code.',
      'transfer_fail': 'Transfer Fail',
      'this_month': 'This month',
      '3_month': '3 month',
      'last_month': 'Last month',
      'custom_month': 'Custom',
      'store_management': 'Store management',
      'merchant_certification': 'Merchant certification',
      'auth_complete': 'Authentication complete',
      'merchant_authentication': 'Merchant authentication',
      'next': 'Next',
      'please_input_login_and_password_and_domain':
          'Please input login, password and select domain.',
      'merchant_login_id': 'Merchant login ID',
      'merchant_login_password': 'Merchant login password',
      'choose_domain': 'Choose domain',
      'login_info_is_same_as_back_office_login':
          'The merchant login information is the same as the back office login information.',
      'id_must_be_more_than_8_characters': 'ID must be more than 8 characters',
      'password_must_be_more_than_6_characters':
          'Password must be more than 6 characters',
      'domain_must_selected': 'Domain must be selected',
      'merchant_authentication_confirm': 'Confirmation of shop',
      'merchant_auth': 'Merchant authentication',
      'merchant_verification_code':
          "Please enter the authentication number sent to the store owner's cell phone.",
      'merchant_phone_change_guide':
          'The mobile number of the administrator registered in the back office.Attempt to authenticate.If your mobile number is incorrect, change your mobile number in the "Shop >Management Information" menu in the back office.',
      'phone_auth_number': 'Authentication number',
      'merchant_auth_completed': 'Registration complete',
      'merchant_uncertified': 'Merchant not certified',
      'merchant_authentication_has_been_completed':
          'Merchant registration has been completed',
      'merchant_login_fail': 'Merchant login Fail',
      'reward_empty_wallet':
          'There are no rewardable wallets. Please create a wallet',
      'reward_many_wallet':
          'There are more than 2 rewardable wallets. Please select your wallet and scan it again',
      'remittance': 'Remittance',
      'currency_exchange': 'Currency Exchange',
      'reward_success': 'Reward Success.',
      'reward_not_issued': 'Reward not issued',
      'reward_expired': 'Reward expired.',
      'reward_canceled': 'Reward canceled.',
      'reward_bad_amount': 'Bad token amount.',
      'reward_rewarded': 'Already rewarded.',
      'reward_not_rewarded': 'Not rewarded.',
      'reward_fail': 'Reward fail',
      'export_vixco_address': 'Export VIXCO Address',
      'import_vixco_address': 'Import VIXCO Address',
      'create_vixco_address': 'Create VIXCO Address',
      'vixco_address_manager': 'VIXCO address Manager',
      'import': 'Import',
      'export': 'Export',
      'backup_complete': 'Backup Complete',
      'invalid_sorting': 'Invalid Sorting',
      'import_vixco_verify_guide':
          'When VIXCO address import is completed, the currently registered address will be changed. For recovery, back up the current address by exporting the VIXCO address before proceeding.',
      'import_vixco_address_success': 'VIXCO address has been created.',
      'import_vixco_address_guide':
          'You can now use your new VIXCO address in the Big Pay app.',
      'import_vixco_mnemonic_phase_guide1':
          'Please enter the seed syntax of the address to import',
      'import_vixco_mnemonic_phase_guide2':
          'For the seed phrase, enter the 12 words displayed when backing up the key in order. Separate each word with a space.',
      'seed_phrase': 'Seed phrase',
      'input_seed_phrase': 'Input Seed phrase',
      'vixco_seed_phrase_history': 'VIXCO Seed phrase history',
      'check_vixco_seed_phrase': 'Check VIXCO Seed phrase',
      'check_vixco_seed_phrase_guide':
          'This is the seed phrase for the VIXCO token. Write it down on a notepad and keep it in a safe place. The next step will ask you to re-enter these phrases (in order).',
      'choose_each_word': 'Choose each word in the order shown',
      'protected_wallet':
          'Protected wallet.\nYou are responsible for keeping your account seed phrase safe',
      'empty_keyindex': 'Empty Keyindex',
      'import_caution_guide1':
          'Only one VIXCO address can be used.\nImport replaces an existing address.',
      'import_caution_guide2':
          'To restore the old address, use VIXCO Address Export to back up the old address before proceeding.',
      'import_fail': 'Import Fail',
      'create_vixco_address_success': 'VIXCO address has been created.',
      'create_vixco_address_passCode_guide':
          'Check the seed syntax for VIXCO address management. Back up and keep the seed phrase according to the screen.',
      'export_caution_guide1':
          'Check the seed syntax for VIXCO address management.',
      'export_caution_guide2':
          'To manage the safe exchange of VIXCO addresses, we proceed with the seed syntax verification step. Follow the on-screen instructions to back up and keep the seed syntax.',
      'export_caution_guide3':
          'You are responsible for keeping your seed phrase safe.',
      'seed_phrase_backup_complete': 'Seed phrase backup complete.',
      'issue_temp_password': 'Issuing a temporary password',
      'issue_temp_password_input_id':
          'Enter the ID to issue a temporary password',
      'issue_temp_password_reset_continue':
          'Reset the existing password to a temporary password. Press the “Reset” button to proceed.',
      'issue_temp_password_reset': 'Reset',
      'issue_temp_password_send_sms':
          'A temporary password has been sent via SMS.',
      'issue_temp_password_complete_guide':
          'Log in using the temporary password \nand change it to a new password '
              '\nin “Setting > Profile > Change Password”',
      'temp_password': 'Temporary password :',
      'press_reset_to_initialize': 'Press reset to initialize new password.'
    },
    'ko': {
      'big_pay': "빅스페이",
      'ok': '확인',
      'cancel': '취소',
      'add_payment_method': '지갑정보 등록',
      'share_my_address': '주소 공유',
      'sent': '출금',
      'received': '입금',
      'transfer_success': '송금이 완료되었습니다.',
      'time': '출금시각',
      'from': '출금주소',
      'to': '입금주소',
      'tx_id': '거래ID',
      'note': '메모',
      'yes': '예',
      'no': '아니요',
      'tx_id': '거래 식별자',
      'note': '메모',
      'readset': 'ReadSet',
      'writeset': 'WriteSet',
      'confirm_transfer_information': '송금정보를 확인하세요.',
      'txmessage': '거래메모',
      'add': '추가',
      'balance': '잔액',
      'contacts': '연락처로 선택',
      'address': '주소로 선택',
      'enter_phone_number_or_email_address': '전화번호 또는 Email 주소를 입력해주세요',
      'recent': '최근사용',
      'transfer_to': 'Transfer to',
      'transfer': 'Transfer',
      'enter_address': '주소를 입력하세요.',
      'my_accounts': '보유주소 정보',
      'please_select_account_to_use_for_payment': '결제 등록할 주소를 선택해 주세요.',
      'enter_your_passcode': '간편 비밀번호를 입력하십시오.',
      'reset_passcode': '다시 입력',
      'create_account': '신규 주소 생성',
      'create_account_success': '신규 주소가 생성되었습니다.',
      'info': '정보',
      'information': '정보',
      'fail': '실패',
      'success': '성공',
      'error': '오류',
      'warning': '주의',
      'enter_account_name': '사용할 주소의 별칭을 입력하세요.',
      'select_a_coin': '토큰종류를 선택하세요.',
      'search_coin': '토큰 검색',
      'suggested': 'Suggested',
      'all_coins': '사용할 토큰을 선택하세요.',
      'sign_up': '회원등록',
      'create_your_passcode': '거래에 사용할 간편 비밀번호를 등록합니다.',
      'add_payment_address': '사용할 주소를 입력해 주세요.',
      'payment_address': '결제주소 주소',
      'add_payment_method_success': '결제 정보 등록에 성공하였습니다.',
      'enter_wallet_name': '사용할 명칭을 입력하세요.',
      'ex_my_wallet': '(예: 내 지갑)',
      'ex_account_name': '(예: 주소별칭)',
      'select_wallet_color': '색상을 선택하십시오.',
      'qr_code': 'QR코드 보기',
      'reenter_your_passcode': '간편 비밀번호를 다시한번 입력하세요.',
      'i_already_have_a_wallet': '가입한 ID가 있습니다.',
      'most_secure_platform_that_makes_it_easy_to_buy_sell_and_store_crypto':
          '가맹점과 소비자를 연결해 주는 블록체인 플랫폼',
      'do_not_have_an_account_q': 'ID가 아직 없나요? ',
      'login_to_your_account': '로그인 정보를 입력해 주세요.',
      'email_id': 'Email 주소',
      'password': '로그인 비밀번호',
      'confirm_password': '비밀번호 확인',
      'keep_me_logged_in': '로그인유지',
      'login': '로그인',
      'find_password': '로그인 비밀번호 찾기',
      'change_password': '로그인 비밀번호 변경',
      'enter_your_current_password': '사용중인 비밀번호를 입력하세요.',
      'enter_your_new_password': '새로 사용할 비밀번호를 입력하세요',
      'receive_service_related_notification': '서비스 관련 공지를 받습니다.',
      'marketing_notification': '이벤트',
      'receive_marketing_related_notification': '마켓팅 관련 안내를 받습니다.',
      'forgot_your_password_q': '로그인 비밀번호를 잊으셨나요?',
      'my_wallet': '등록된 지갑정보',
      'confirm': '확인',
      'pay': '결제하기',
      'reward': '적립하기',
      'your_accounts_are_no_available': '등록된 주소가 없습니다.',
      'phone_number': '전화번호',
      'logout': '로그아웃',
      'notification': '알림',
      'service_notification': '서비스 알림',
      'setting': '설정',
      'add_delete_payment_method': '지갑정보 추가/삭제',
      'passcode': '간편 비밀번호 변경',
      'payment_method': '지갑정보 관리',
      'others': '기타',
      'edit_wallet_name': '지갑명을 수정합니다.',
      'terms_of_service': '약관 동의',
      'terms_of_service_view': '서비스 이용약관',
      'version': '버젼',
      'welcome_abroad': '빅스페이 등록을 환영합니다!',
      'account_has_been_created': '정상적으로 등록되었습니다.',
      'transfer_to': '송금하기',
      'transfer': '송금',
      'reset': '초기화',
      'create_new_user_account': '회원 가입',
      'add_account': '주소 추가',
      'delete_account': '계정 삭제',
      'delete_account_q': '계정을 삭제하시겠습니까?',
      'please_enter_mobile_number': '휴대폰 번호를 입력하세요.',
      'please_enter_valid_mobile_number': '유효한 휴대폰 번호를 입력하세요.',
      'enter_valid_email': '유효한 이메일을 입력하세요.',
      'please_input_text': '값을 입력해 주세요.',
      'name_must_be_more_than_4_charater': '이름은 최소 4자 이상입니다.',
      'max': '최대',
      'create_new_wallet': '새로운 계정을 만들겠습니다.',
      'login_fail_please_check_input_field':
          '로그인 실패 \n전화번호와 비밀번호를 바르게 입력해 주세요.',
      'profile': '프로필정보',
      'app': '앱',
      'continue': '다음',
      'password_must_be_more_than_6_charater': '비밀번호는 6자리 이상입니다.',
      'password_and_confirmation_password_are_different': '입력한 2개의 비밀번호가 다릅니다.',
      'telephone_number_must_be_of_9_12_digit': '전화번호는 9~12자리를 입력해야 합니다.',
      'en': '영어',
      'ko': '한국어',
      'kk': '카자흐어',
      'ru': '러시아어',
      'code': '코드',
      'language_setting': '언어설정',
      'language': '언어',
      'default_language': '기본언어',
      'edit': '수정',
      'fail_to_fetch_posts': '조회된 결과가 없습니다.',
      'debug_only': '개발자 전용',
      'scan_qr_code': 'QR 코드를 스캔합니다.',
      'flash_on': '플래시 켜짐',
      'flash_off': '플래시 꺼짐',
      'use_front_camera': '전면 카메라 사용',
      'use_back_camera': '후면 카메라 사용',
      'pause': '중지',
      'resume': '시작',
      'loading': '초기화 중...',
      'add_txmessage': '거래메시지 추가',
      'edit_txmessage': '거래메시지 편집',
      'enter_message': '메시지를 입력해 주세요...',
      'payment': '결제',
      'payment_success': '결제가 완료되었습니다.',
      'invalid_passcode': '간편 비밀번호가 틀렸습니다.',
      'invalid_password': '잘못된 비밀번호를 입력하셨습니다.',
      'qr_scan': 'QR스캔',
      'mandatory': '필수항목',
      'option': '선택입력',
      'user_name': '고객명',
      'already_have_user_account': '이미 가입된 정보가 있습니다.',
      'i_agree_terms': '약관에 동의합니다.',
      'account_list_is_empty_create_an_account': '보유주소가 없습니다.\n주소를 생성하십시요.',
      'enter_mobile_number_for_verification': '인증을 위하여 핸드폰 번호를 입력해주세요',
      'send_verification_code': '인증번호 전송',
      'verification_number': '인증번호',
      'invalid_verification_number': '잘못된 인증번호를 입력하셨습니다.',
      'valid_time_is_expired': '인증번호의 유효시간이 지났습니다.',
      'remaining_time': '남은 시간',
      're-send': '재전송',
      'invalid_phonenumber': '잘못된 폰 번호입니다.',
      'no_registered_tokens': '등록된 토큰이 없습니다.',
      'waiting_for_approval': '라이센스 승인을 기다리는 중입니다.',
      'license_pause': '라이센스가 일시 중지되었습니다.',
      'license_disposal': '라이센스가 폐기되었습니다.',
      'license_expired': '라이센스가 만기되었습니다.',
      'license_invalid': '라이센스가 유효하지 않습니다.',
      'license_invalid_store': '로그인한 상점의 라이센스가 아닙니다. 초기화 하시겠습니까?',
      'app_update_title': 'App 업데이트',
      'app_update_context': 'App이 업데이트 되었습니다.',
      'update': '업데이트',
      'dismiss': '취소',
      'exit': '종료',
      'restart': '재시작',
      'restart_app': '앱을 재시작 하여야 합니다.',
      'assign_token': 'Token 연결',
      'select_assign_token': 'Token을 선택하세요',
      'assigned_token_list': '연결된 Token List',
      'addable_token_list': '추가 가능한 Token',
      'krw': 'KRW',
      'no_data_available_now': '표시 할 데이터가 없습니다.',
      'exchange_rate': '기준시세',
      'assign_token_success': '토큰 연결이 완료되었습니다',
      'cancel_assign': 'Token 할당취소',
      'remove_account': '주소를 삭제하시겠습니까?',
      'transfer_date': '출금시간',
      'assign_token_fail': '토큰연결에 실패했습니다. 잠시후 다시 시도해 주십시오',
      'empty_token': 'Token이 비어있습니다',
      'staking_info': 'Staking',
      'staking_address': 'Staking 주소',
      'management': '관리',
      'copied': '복사 완료',
      'link_has_been_copied_to_clipboard': '주소가 성공적으로 복사되었습니다.',
      'delete_complete': '등록계좌 삭제완료',
      'bank_account_delete': '계좌가 삭제되었습니다.',
      'ethereum': 'Ethereum',
      'vixco': 'VIXCO',
      'delete_wallet': '지갑을 삭제하시겠습니까?',
      'maximum_address': '주소는 20개까지만 생성가능합니다.',
      'mnemonic': '니모닉',
      'invalid_qr_code': '잘못된 QR코드입니다.',
      'transfer_fail': '송금에 실패하였습니다.',
      'this_month': '이번 달',
      '3_month': '3개월',
      'last_month': '지난 달',
      'custom_month': '사용자정의',
      'store_management': '가맹점관리',
      'merchant_certification': '가맹점 인증',
      'auth_complete': '인증완료',
      'merchant_authentication': '가맹점 인증',
      'next': '다음',
      'please_input_login_and_password_and_domain':
          '가맹점 확인을 위하여  로그인 정보를 입력해 주세요',
      'merchant_login_id': '가맹점 로그인 ID',
      'merchant_login_password': '가맹점 로그인 비밀번호',
      'choose_domain': '가맹점 Domain',
      'login_info_is_same_as_back_office_login':
          '가맹점 로그인 정보는 백오피스 로그인 정보와동일합니다.',
      'id_must_be_more_than_8_characters': 'ID는 8자 이상이어야 합니다.',
      'password_must_be_more_than_6_characters': '암호는 6자 이상이어야 합니다.',
      'domain_must_selected': '도메인을 선택해야 합니다.',
      'merchant_authentication_confirm': '상점주 확인',
      'merchant_auth': '가맹점 인증',
      'merchant_verification_code': "상점주의 휴대폰으로 발송된 인증번호를 입력해 주세요",
      'merchant_phone_change_guide':
          '백오피스에 등록된 관리자의 휴대폰 번호로 인증을 시도합니다. 휴대 번호가 틀리면 백오피스의  “상점>관리정보”메뉴에서  휴대폰 번호를 변경하십시오.',
      'phone_auth_number': '인증번호',
      'merchant_auth_completed': '가맹점 인증 완료',
      'merchant_uncertified': '가맹점 미인증',
      'merchant_authentication_has_been_completed': '가맹점 인증이 완료되었습니다.',
      'merchant_login_fail': '가맹점 로그인이 실패하였습니다.',
      'reward_empty_wallet': '적립이 가능한 지갑이 없습니다. 지갑을 생성해 주세요',
      'reward_many_wallet': '적립 가능한 지갑이 2개 이상입니다. 지갑을 선택 후 다시 스캔해 주세요',
      'remittance': '송금신청',
      'currency_exchange': '환전신청',
      'reward_success': '적립에 성공하였습니다.',
      'reward_not_issued': '발급되지 않은 적립입니다.',
      'reward_expired': '만료된 적립입니다.',
      'reward_canceled': '적립이 취소되었습니다.',
      'reward_bad_amount': '적립금이 잘못되었습니다.',
      'reward_rewarded': '이미 적립되었습니다.',
      'reward_not_rewarded': '적립이 아닙니다.',
      'reward_fail': '적립에 실패하였습니다.',
      'export_vixco_address': 'VIXCO 주소내보내기',
      'import_vixco_address': 'VIXCO 주소가져오기',
      'create_vixco_address': 'VIXCO 주소생성',
      'vixco_address_manager': 'VIXCO 주소 관리',
      'import': '가져오기',
      'export': '내보내기',
      'backup_complete': '백업완료',
      'invalid_sorting': '순서가 잘못되었습니다.',
      'import_vixco_verify_guide':
          'VIXCO 주소 가져오기를  완료하면 지금 등록되어있는 주소가 교체됩니다. 복구를 위해 VIXCO주소 내보내기로 사용중인 주소를 백업 후 진행하십시요.',
      'import_vixco_address_success': 'VIXCO주소를 가져오기가 완료되었습니다.',
      'import_vixco_address_guide': '이제 빅스페이 앱에서 새로운 VIXCO 주소를 사용할 수 있습니다.',
      'import_vixco_mnemonic_phase_guide1': '가져올 주소의 시드 구문을 입력해 주세요',
      'import_vixco_mnemonic_phase_guide2':
          '시드구문은 키 백업 시 표시된 12개의 단어를 순서대로 입력하십시오. 각 단어는 띄어쓰기로 구분해 주십시요.',
      'seed_phrase': '시드구문',
      'input_seed_phrase': '여기에 시드구문을 입력해 주세요',
      'vixco_seed_phrase_history': 'VIXCO 시드 구문 기록',
      'check_vixco_seed_phrase': '시드 구문을 확인해주세요.',
      'check_vixco_seed_phrase_guide':
          'VIXCO 토큰의 시드 구문입니다.메모지에 적어 안정한 장소에 보관하십시오. 다음 단계에 이 구문을 (순서대로) 다시 입력하라는메시지가 표시됩니다.',
      'choose_each_word': '표시된 순서대로 각 단어를 선택하세요',
      'protected_wallet': '지갑을 보호했습니다. 계정 시드 구문을 안전하게\n보관할 책임은 귀하에게 있습니다.',
      'empty_keyindex': 'Keyindex가 비어있습니다.',
      'import_caution_guide1': 'VIXCO 주소는 1개만 사용가능합니다.\n가져오기는  기존 주소를 교체합니다.',
      'import_caution_guide2': '사용중인 주소의 복구를 위해 VIXCO주소 내보내기를 이용해 백업 후 진행하십시요.',
      'import_fail': '가져오기를 실패하였습니다.',
      'create_vixco_address_success': 'VIXCO 주소가 생성되었습니다.',
      'create_vixco_address_passCode_guide':
          'VIXCO 주소 관리를 위해 시드구문을 확인합니다. 화면에 따라 시드구문을 백업하고 보관하십시요.',
      'export_caution_guide1': 'VIXCO주소 관리를 위해\n시드구문을 확인합니다.',
      'export_caution_guide2':
          'VIXCO 주소의 안전한 관리를 위해 시드구문 확인을 진항햅니다. 화면의 안내에 따라 시드구문을 백업하고 보관하십시요.',
      'export_caution_guide3': '시드 구문을 안전하게 보관할 책임은\n 귀하에게 있습니다.',
      'seed_phrase_backup_complete': '시드 구문이 백업되었습니다.',
      'issue_temp_password': '임시 비밀번호 발급',
      'issue_temp_password_input_id': '임시비밀번호를 발급할 ID 입력해주세요',
      'issue_temp_password_reset_continue':
          '기존의 비밀번호를\n임시 비밀번호로 초기화 합니다. \n진행하시려면 “초기화” 버튼을 누르세요.',
      'issue_temp_password_reset': '초기화',
      'issue_temp_password_send_sms': '임시 비밀번호가 SMS로 발송되었습니다.',
      'issue_temp_password_complete_guide':
          '임시 비밀번호를 사용해 로그인 후 “더보기 > 프로필정보 > 로그인비밀번호 변경” 에서 새로운 비밀번호로 변경하십시요.',
      'temp_password': '임시비밀번호 :',
      "press_reset_to_initialize": '비밀번호 초기화를 진행합니다.'
    },
    'ru': {},
    'kk': {},
    'zh': {},
    'code': {}
  };

  String getString(String? value) {
    String text = value ?? '';

    if (value != null && value.isNotEmpty) {
      if (_localizedValues.containsKey(AppLocalizations.languageCode!)) {
        if (_localizedValues[AppLocalizations.languageCode!]!
            .containsKey(value)) {
          text = _localizedValues[AppLocalizations.languageCode!]![value]!;

          if (showCode) {
            String? code =
                showUserInputCode ? value : _localizedValues['code']![value];
            text = '[$code]$text';
          }
        } else {
          if (!kReleaseMode) {
            // 다국어 번역 확인이 필요할 경우 아래 주석 풀 것
            //debugPrint('I18N string not found: [${AppLocalizations.languageCode}]$value');
          }
        }
      }
    }

    return text;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      ['en', 'ko', 'ru', 'kk', 'zh'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture<AppLocalizations>(AppLocalizations(locale));
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
