import 'package:flutter/material.dart';
import 'package:yollet/themeStyle.dart';

class DefaultInputDecoration extends InputDecoration {
  const DefaultInputDecoration({
    icon,
    labelText,
    labelStyle,
    helperText,
    helperStyle,
    hintText,
    hintStyle,
    hintMaxLines,
    errorText,
    errorStyle,
    errorMaxLines,
    hasFloatingPlaceholder = true,
    isDense,
    contentPadding,
    prefixIcon,
    prefix,
    prefixText,
    prefixStyle,
    suffixIcon,
    suffix,
    suffixText,
    suffixStyle,
    counter,
    counterText,
    counterStyle,
    filled,
    fillColor = ThemeColors.white,
    errorBorder,
    focusedBorder,
    focusedErrorBorder,
    disabledBorder,
    enabledBorder,
    border,
    /*
    border = new OutlineInputBorder(
      borderRadius: new BorderRadius.circular(5.0.w),
      borderSide: new BorderSide(),
    ),
    */
    enabled = true,
    semanticCounterText,
    alignLabelWithHint,
  }) : super(
          icon: icon,
          labelText: labelText,
          labelStyle: labelStyle,
          helperText: helperText,
          helperStyle: helperStyle,
          hintText: hintText,
          hintStyle: hintStyle,
          hintMaxLines: hintMaxLines,
          errorText: errorText,
          errorStyle: errorStyle,
          errorMaxLines: errorMaxLines,
          // hasFloatingPlaceholder: hasFloatingPlaceholder,
          isDense: isDense,
          contentPadding: contentPadding,
          prefixIcon: prefixIcon,
          prefix: prefix,
          prefixText: prefixText,
          prefixStyle: prefixStyle,
          suffixIcon: suffixIcon,
          suffix: suffix,
          suffixText: suffixText,
          suffixStyle: suffixStyle,
          counter: counter,
          counterText: counterText,
          counterStyle: counterStyle,
          filled: filled,
          fillColor: fillColor,
          errorBorder: errorBorder,
          focusedBorder: focusedBorder,
          focusedErrorBorder: focusedErrorBorder,
          disabledBorder: disabledBorder,
          enabledBorder: enabledBorder,
          border: border,
          enabled: enabled,
          semanticCounterText: semanticCounterText,
          alignLabelWithHint: alignLabelWithHint,
        );
}
